/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "ap-southeast-1",
  aws_user_pools_id: "ap-southeast-1_E2biAnMuS",
  aws_user_pools_web_client_id: "5r4snaib2vg986j9eh6u4u92g8",
};

export default awsmobile;
